CREATE TABLE `player-stats` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`rk` integer,
	`date` text,
	`age` text,
	`tm` text,
	`opp` text,
	`gs` integer,
	`mp` integer,
	`fg` integer,
	`fga` integer,
	`fgPct` integer,
	`threeP` integer,
	`threePA` integer,
	`threePPct` integer,
	`ft` integer,
	`fta` integer,
	`ftPct` integer,
	`orb` integer,
	`drb` integer,
	`trb` integer,
	`ast` integer,
	`stl` integer,
	`blk` integer,
	`tov` integer,
	`pf` integer,
	`pts` integer,
	`gmSc` integer,
	`seasonType` text
);
