import { sqliteTable, text, integer } from "drizzle-orm/sqlite-core";

export const playerStatsTable = sqliteTable("player_stats", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  player_id: text("player_id"),
  year: integer("year"),
  rk: integer("rk"),
  date: text("date"),
  age: text("age"),
  tm: text("tm"),
  away: integer("away", { mode: "boolean" }),
  opp: text("opp"),
  wdiff: text("wdiff"),
  gs: integer("gs", { mode: "boolean" }),
  mp: integer("mp", { mode: "number" }),
  fg: integer("fg", { mode: "number" }),
  fga: integer("fga", { mode: "number" }),
  fgPct: text("fg_pct"),
  threeP: integer("three_p", { mode: "number" }),
  threePA: integer("three_pa", { mode: "number" }),
  threePPct: text("three_p_pct"),
  ft: integer("ft", { mode: "number" }),
  fta: integer("fta", { mode: "number" }),
  ftPct: text("ft_pct"),
  orb: integer("orb", { mode: "number" }),
  drb: integer("drb", { mode: "number" }),
  trb: integer("trb", { mode: "number" }),
  ast: integer("ast", { mode: "number" }),
  stl: integer("stl", { mode: "number" }),
  blk: integer("blk", { mode: "number" }),
  tov: integer("tov", { mode: "number" }),
  pf: integer("pf", { mode: "number" }),
  pts: integer("pts", { mode: "number" }),
  gmSc: text("gm_sc"),
  seasonType: text("season_type"),
});
